/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fifa_2019;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import packg.Conn;

/**
 *
 * @author jishant
 */
public class Age_Wise_Best extends javax.swing.JFrame {

    /**
     * Creates new form Age_Wise_Best
     */
    public Age_Wise_Best() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Overall", "Value", "Height", "Weight", "Release_Clause"
            }
        ));
        jScrollPane1.setViewportView(jTable4);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Graphical View -->");

        jRadioButton1.setText("Line Chart");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            Connection con;
            con =null;
            String driverName = "org.apache.hive.jdbc.HiveDriver";	      	
            try 
            {
                Class.forName(driverName);
		con = DriverManager.getConnection("jdbc:hive2://localhost:10000/DB", "hive", "");
            }
            catch(Exception e)
            {
               System.out.println("error in connection");
            }
            Statement stmt2 = con.createStatement();
            String sql = "select * from FIFA order by age,overall desc Limit 10";
            ResultSet rs1 = stmt2.executeQuery(sql);
            Vector head = new Vector();
            head.addElement("ID");
            head.addElement("Name");
            head.addElement("Age");
            head.addElement("Overall");
            head.addElement("Value");
            head.addElement("Height");
            head.addElement("Weight");
            head.addElement("Release_clause");
            Vector rows = new Vector();

            while (rs1.next()) {
                Vector innerVector = new Vector();
                innerVector.addElement(rs1.getObject("FIFA.ID") + "");
                innerVector.addElement(rs1.getObject("FIFA.name") + "");
                innerVector.addElement(rs1.getObject("FIFA.age") + "");
                innerVector.addElement(rs1.getObject("FIFA.overall") + "");
                innerVector.addElement(rs1.getObject("FIFA.value") + "");
                innerVector.addElement(rs1.getObject("FIFA.height") + "");
                innerVector.addElement(rs1.getObject("FIFA.weight") + "");
                innerVector.addElement(rs1.getObject("FIFA.release_clause") + "");
                rows.addElement(innerVector);
            }

            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(rows,head);

            jTable4.setModel(model);

        } catch (Exception e) {

            System.out.println(e.getMessage());

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       
        try
        {
        Connection con= Conn.getCon();
         Statement stmt3 = con.createStatement();
            String sql = "select age,overall from FIFA order by overall";
        ResultSet rs1 = stmt3.executeQuery(sql);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset(); 
        while(rs1.next())
        {
         dataset.addValue( 
         Double.parseDouble(rs1.getString("age")),rs1.getString("overall"),rs1.getString("age"));
        }
        JFreeChart chart=ChartFactory.createLineChart("Fit Players","age","overall",dataset,PlotOrientation.VERTICAL,  
        true,true,false);
        ChartFrame frame=new ChartFrame("Query Chart",chart);
        frame.setVisible(true);
        frame.setSize(500,500);        
}
catch(Exception e)
{
    System.out.println("Error");
}
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Age_Wise_Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Age_Wise_Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Age_Wise_Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Age_Wise_Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Age_Wise_Best().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
